const mongoose = require("mongoose");

const invoiceSettingsSchema = new mongoose.Schema({
  singleton:  { type: String, default: "settings", unique: true },
  businessName: { type: String, default: "" },
  businessAddress: {
    line1: { type: String, default: "" },
    line2: { type: String, default: "" },
    city:  { type: String, default: "" },
    state: { type: String, default: "" },
    stateCode: { type: String, default: "" },
    pincode: { type: String, default: "" },
  },
  businessPhone: { type: String, default: "" },
  businessEmail: { type: String, default: "" },
  businessWebsite: { type: String, default: "" },
  gstin:    { type: String, default: "" },
  pan:      { type: String, default: "" },
  cin:      { type: String, default: "" },
  logoUrl:  { type: String, default: "" },
  signatureUrl: { type: String, default: "" },
  stampUrl:    { type: String, default: "" },
  defaultStateCode: { type: String, default: "" },
  invoicePrefix: { type: String, default: "INV" },
  invoiceStartNo: { type: Number, default: 1 },
  currentInvoiceNo: { type: Number, default: 0 },
  proformaPrefix: { type: String, default: "PRO" },
  currentProformaNo: { type: Number, default: 0 },
  creditNotePrefix: { type: String, default: "CRN" },
  currentCreditNoteNo: { type: Number, default: 0 },
  debitNotePrefix: { type: String, default: "DBN" },
  currentDebitNoteNo: { type: Number, default: 0 },
  poPrefix: { type: String, default: "PO" },
  currentPoNo: { type: Number, default: 0 },
  paymentPrefix: { type: String, default: "REC" },
  currentPaymentNo: { type: Number, default: 0 },
  adjustmentPrefix: { type: String, default: "ADJ" },
  currentAdjustmentNo: { type: Number, default: 0 },
  defaultPaymentTerms: { type: Number, default: 30 },
  defaultTaxType: { type: String, enum: ["igst", "cgst_sgst"], default: "cgst_sgst" },
  enableRoundOff: { type: Boolean, default: true },
  defaultCurrency: { type: String, default: "INR" },
  financialYearStart: { type: Number, default: 4 },
  bankName:    { type: String, default: "" },
  bankAccount: { type: String, default: "" },
  bankIFSC:    { type: String, default: "" },
  bankBranch:  { type: String, default: "" },
  defaultNotes: { type: String, default: "" },
  defaultTerms: { type: String, default: "" },
  defaultTemplate: { type: mongoose.Schema.Types.ObjectId, ref: "InvoiceTemplate", default: null },
}, { timestamps: true });

module.exports = mongoose.model("InvoiceSettings", invoiceSettingsSchema);
